### ISSUE TITLE
P-007: Looking at the Goal tracker (UI aspects)

### ISSUE THREAD

**Issue by Mwamitovi** [BuildForSDG/PulaniFront#12]
As a Pulani stakeholder, i'd like to review the GOAL TRACKER feature.

**Description:** We aim to encourage users to be consistent in their data-entry efforts. And we believe tracking their goals would play a part.

**Acceptance Criteria:** 
- Wireframe (or Mock-up) of the goal-tracker and clearly depicting what records it will show.

**Comment by Mwamitovi** [comment]
@halimahbukirwa, @BryanCI and @Nataanthoni 
Here is the proposed Goal tracker module that we can display at the dashboard. 

Some key things to note:
- Ignore the used colors for now (those are bound to change)
- The top most cards, when clicked/tapped (or whatever is deemed more user friendly) could open up to allow the user to set a goal (include target, period, etc)
- The middle cards are basically for tracking progress
- The bottom cards (graphs) or graphs, can be clicked (or otherwise) to show the product/service form intelligently based on a user's job.
- To manage the MVP complexity, this dashboard can be developed in phases in order to first ship with basic actions/functions and UI
<br/>

![pulani_dashboard](https://user-images.githubusercontent.com/29486552/83348869-e6914e80-a338-11ea-9d5e-7dd78eb791c6.png)

**Comment by Nataanthoni** [comment]
Hello Front End Team,

Thank you for putting this together. I think it's good. in order to improve or help some of us understand it better, please do give the following clarifications;

- Whose dashboard is that? In my opinion we are supposed to have about 2 dashboards. The end users and admins. Or is there a hidden way admins shall access the user data? I think this is important because the entered user data needs some sort of analysis and approval before being trusted yet also, the user does not want his business data publicly available.
- When is the dashboard accessible. Is this immediately after login or?
- Where are the links to punch in or view daily business performance data?
- Profiles and log out etc? Could these be made more visible if available?
- Who sees the dashboard? How is it secured?
- Is it possible for an admin to log in and view end user data yet not possible for a user to view a colleague's?
- As you might have also noticed, we need a homepage too. Please make sure you share with us this so we could see and advice accordingly, unless you think this is not needed.
- Where is the request a loan button/link or is this no longer necessary?

Thank you!

**Comment by Mwamitovi** [comment]
On behalf of the frontend team (who lately are occasionally online), let me answer many of these questions here: https://github.com/BuildForSDG/Team-270-PulaniFront/issues/12#issuecomment-636661844

>Whose dashboard is that? In my opinion we are supposed to have about 2 dashboards. The end users and admins. Or is there a hidden way admins shall access the user data? I think this is important because the entered user data needs some sort of analysis and approval before being trusted yet also, the user does not want his business data publicly available.

- As mentioned earlier, for the MVP, we are focused on the end user. So this is a User's dashboard. 
- The Admin dashboard will be done later.
- Being an MVP, analysis and approval are beyond scope (but should rank high in version-2)

>When is the dashboard accessible. Is this immediately after login or?

- Kindly note that every user is required to login, first. 
- After login, a user directly lands at their dashboard.

>Where are the links to punch in or view daily business performance data?

- The actual usability/data-entry point is not reflected in the dashboard.
But the frontend team has two approaches so far in mind,
1. Make the top-most cards clickable for one to enter/update their GOAL, and the bottom-most graphs clickable for one to add their records immediately.
2. To create a simple `<a>` anchor links at the top of each section for a user to enter the respective data.
Either way, the intention is to have different GOAL and PROGRESS forms, for any goal that a user would want to track.

- Daily business performance data: We thought about this one but since there is no way to guarantee that a user will enter data on a daily, thus the statistics reflected in the dashboard. **Therefore the dashboard shall be the central view for this task.**

>Profiles and log out etc? Could these be made more visible if available?

All these shall catered for within the **small icon (at the top-right)**, and also shall be reflected in the sidebar.

>Who sees the dashboard? How is it secured?

Since everyone comes within via login, each sees a customized dashboard (with their stats) thus security is achieved that way too by enforcing login, first.

>Is it possible for an admin to log in and view end user data yet not possible for a user to view a colleague's?

This is definitely an issue of user rights which is totally possible.
**As earlier mentioned, Admin will be considered later but all we'll need is to start managing permissions.** And then display given views based on user roles/permissions.

>As you might have also noticed, we need a homepage too. Please make sure you share with us this so we could see and advice accordingly, unless you think this is not needed.

Given the user journey highlighted above, **for every user their home page is their dashboard.**

>Where is the request a loan button/link or is this no longer necessary?

We are greatly rethinking the entry point into the loan request module.
For one, based on the goal tracker, the frontend team is thinking along these lines:
1. We can intelligently sieve (based on their goals/performance) which users are ready to engage with loan's officers (and possibly then include a "Loan Request" link in the sidebar) 
2. Or we can present a "Need a Loan" link within the sidebar, which when clicked by a user broadcasts a notification to various partners (loan officers or whoever) to then get in touch with our user.

As you notice, the loan request module is considered beyond MVP and that gives us more time to align on a given direction.

@halimahbukirwa and @BryanCI will definitely come in to expound on any of the above approaches but I hope a lot of things are now in perspective.

Thanks.

**Comment by Nataanthoni** [comment]
Great response @Mwamitovi . I just hope you noticed there are some more useful questions you have omitted. Nonetheless, thank you for the answers.

**Comment by Mwamitovi** [comment]
Oh, thanks @Nataanthoni .


> Great response @Mwamitovi . I just hope you noticed there are some more useful questions you have omitted. Nonetheless, thank you for the answers.

Response has been updated to fully tackle all questions.
