### ISSUE TITLE
P-006, Update the `README` file

### ISSUE THREAD

**Issue by Mwamitovi** [BuildForSDG/PulaniFront#6]
**Description:** Having set up the project already, we now want to guide the team on how to do the same.

**Acceptance Criteria:**
- Update the `README` file with relevant project info

**Comment by halimahbukirwa** [comment]
Okay

**Comment by Mwamitovi** [comment]
Changes have been made here. @halimahbukirwa, @BryanCI and @Nataanthoni kindly review the associated PR.
